// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a list of all addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/address"
                ],
                "summary": "List all addresses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_AddressDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new address with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/address"
                ],
                "summary": "Create a new address",
                "parameters": [
                    {
                        "description": "Address",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AddressDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AddressDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete an address by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/address"
                ],
                "summary": "Delete an address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/address/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get an address by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/address"
                ],
                "summary": "Get an address by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AddressDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/admin": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a list of all admins.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/admin"
                ],
                "summary": "List all admins",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_AdminDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new admin with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/admin"
                ],
                "summary": "Create a new admin",
                "parameters": [
                    {
                        "description": "Personal Information",
                        "name": "personalInformation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonalInformationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AdminDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete an admin by its ID.",
                "tags": [
                    "/admin"
                ],
                "summary": "Delete an admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/admin/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get an admin by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/admin"
                ],
                "summary": "Get an admin by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AdminDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/analyst": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a list of all analysts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/analyst"
                ],
                "summary": "List all analysts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_AnalystDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new analyst with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/analyst"
                ],
                "summary": "Create a new analyst",
                "parameters": [
                    {
                        "description": "Personal Information",
                        "name": "personalInformation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonalInformationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AnalystDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/analyst/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get an analyst by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/analyst"
                ],
                "summary": "Get an analyst by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analyst ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AnalystDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete an analyst by its ID.",
                "tags": [
                    "/analyst"
                ],
                "summary": "Delete an analyst",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analyst ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/api-key": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a list of all apiKeys.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api-key"
                ],
                "summary": "List all apiKeys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_ApiKeyDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new apiKey with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api-key"
                ],
                "summary": "Create a new apiKey",
                "parameters": [
                    {
                        "description": "ApiKey",
                        "name": "apiKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.ApiKeyDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.ApiKeyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/api-key/{uuid}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get an apiKey by its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api-key"
                ],
                "summary": "Get an apiKey by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ApiKey UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.ApiKeyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete a apiKey by its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api-key"
                ],
                "summary": "Delete a apiKey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ApiKey UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new user with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/auth"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User to create",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.UserDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": [],
                        "BasicAuth": []
                    }
                ],
                "description": "Signs in with the provided credentials",
                "tags": [
                    "/auth"
                ],
                "summary": "Sign in",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Checks the health of the API and its dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/health"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/person": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a list of all persons.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/person"
                ],
                "summary": "List all persons",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_PersonDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new person with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/person"
                ],
                "summary": "Create a new person",
                "parameters": [
                    {
                        "description": "Personal Information",
                        "name": "personalInformation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonalInformationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/person/{document}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get an person by document.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/person"
                ],
                "summary": "Get an person by document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document",
                        "name": "document",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/person/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get an person by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/person"
                ],
                "summary": "Get an person by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Person ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete an person by its ID.",
                "tags": [
                    "/person"
                ],
                "summary": "Delete an person",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Person ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a list of all users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/user"
                ],
                "summary": "List all users",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get a user by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/user"
                ],
                "summary": "Get a user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by its ID.",
                "tags": [
                    "/user"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AddressDTO": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "complement": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "number": {
                    "type": "string",
                    "example": "1234 | S/N"
                },
                "state": {
                    "type": "string",
                    "example": "SC"
                },
                "street": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "zip_code": {
                    "type": "string",
                    "example": "12345-678"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AdminDTO": {
            "type": "object",
            "required": [
                "personal_information"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "personal_information": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonalInformationDTO"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AnalystDTO": {
            "type": "object",
            "required": [
                "personal_information"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "personal_information": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonalInformationDTO"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.ApiKeyDTO": {
            "type": "object",
            "required": [
                "slug",
                "uuid"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.CreditAccountDTO": {
            "type": "object",
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "available_credit": {
                    "type": "number"
                },
                "closed_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "credit_limit": {
                    "type": "number"
                },
                "creditor": {
                    "type": "string"
                },
                "creditor_document": {
                    "type": "string"
                },
                "current_balance": {
                    "type": "number"
                },
                "days_late": {
                    "type": "integer"
                },
                "highest_days_late": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "interest_rate": {
                    "type": "number"
                },
                "last_reported_date": {
                    "type": "string"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "number_of_payments": {
                    "type": "integer"
                },
                "opened_date": {
                    "type": "string"
                },
                "original_amount": {
                    "type": "number"
                },
                "payment_due_day": {
                    "type": "integer"
                },
                "payment_status": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "remaining_amount": {
                    "type": "number"
                },
                "remaining_payments": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "times_late_30_days": {
                    "type": "integer"
                },
                "times_late_60_days": {
                    "type": "integer"
                },
                "times_late_90_days": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.CreditInquiryDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "creditor": {
                    "type": "string"
                },
                "creditor_document": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inquiry_date": {
                    "type": "string"
                },
                "inquiry_type": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "purpose": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.CreditScoreDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "credit_age": {
                    "type": "integer"
                },
                "credit_mix": {
                    "type": "integer"
                },
                "credit_usage": {
                    "type": "integer"
                },
                "default_probability": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "payment_history": {
                    "type": "integer"
                },
                "person_id": {
                    "type": "integer"
                },
                "recent_inquiries": {
                    "type": "integer"
                },
                "risk_level": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "score_date": {
                    "type": "string"
                },
                "score_model": {
                    "type": "string"
                },
                "score_reason": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.DataSourceDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_sync_date": {
                    "type": "string"
                },
                "reliability_score": {
                    "type": "integer"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.DebtDTO": {
            "type": "object",
            "properties": {
                "collection_agency": {
                    "type": "string"
                },
                "collection_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creditor": {
                    "type": "string"
                },
                "creditor_document": {
                    "type": "string"
                },
                "current_amount": {
                    "type": "number"
                },
                "debt_type": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "fees": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "in_collection": {
                    "type": "boolean"
                },
                "interest_rate": {
                    "type": "number"
                },
                "origin_date": {
                    "type": "string"
                },
                "original_amount": {
                    "type": "number"
                },
                "person_id": {
                    "type": "integer"
                },
                "settlement_amount": {
                    "type": "number"
                },
                "settlement_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.EmploymentRecordDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data_source": {
                    "type": "string"
                },
                "employer_document": {
                    "type": "string"
                },
                "employer_name": {
                    "type": "string"
                },
                "employment_type": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_current": {
                    "type": "boolean"
                },
                "job_title": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "salary": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verification_status": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FileDTO": {
            "type": "object",
            "required": [
                "original_name",
                "url"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/file.jpg"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FinancialProfileDTO": {
            "type": "object",
            "properties": {
                "available_credit": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "credit_utilization": {
                    "type": "number"
                },
                "debt_to_income_ratio": {
                    "type": "number"
                },
                "declared_monthly_income": {
                    "type": "number"
                },
                "estimated_monthly_income": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "income_source": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "profile_date": {
                    "type": "string"
                },
                "real_estate_value": {
                    "type": "number"
                },
                "total_assets": {
                    "type": "number"
                },
                "total_liabilities": {
                    "type": "number"
                },
                "total_monthly_payments": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "vehicles_value": {
                    "type": "number"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FraudAlertDTO": {
            "type": "object",
            "properties": {
                "alert_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "detected_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "resolved_by": {
                    "type": "string"
                },
                "resolved_date": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.HealthResponse": {
            "type": "object",
            "properties": {
                "api_status": {
                    "type": "string"
                },
                "cache_status": {
                    "type": "string"
                },
                "database_status": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.LegalRecordDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "court": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "filing_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "person_id": {
                    "type": "integer"
                },
                "process_number": {
                    "type": "string"
                },
                "record_type": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                },
                "resolution_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.NegativeRecordDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract_number": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creditor": {
                    "type": "string"
                },
                "creditor_document": {
                    "type": "string"
                },
                "dispute_date": {
                    "type": "string"
                },
                "dispute_reason": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inclusion_date": {
                    "type": "string"
                },
                "is_disputed": {
                    "type": "boolean"
                },
                "notary": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "process_number": {
                    "type": "string"
                },
                "record_type": {
                    "type": "string"
                },
                "removal_date": {
                    "type": "string"
                },
                "removal_reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_AddressDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "List of items in the current page",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AddressDTO"
                    }
                },
                "total": {
                    "description": "Total number of items available",
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_AdminDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "List of items in the current page",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AdminDTO"
                    }
                },
                "total": {
                    "description": "Total number of items available",
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_AnalystDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "List of items in the current page",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AnalystDTO"
                    }
                },
                "total": {
                    "description": "Total number of items available",
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_ApiKeyDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "List of items in the current page",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.ApiKeyDTO"
                    }
                },
                "total": {
                    "description": "Total number of items available",
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_PersonDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "List of items in the current page",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDTO"
                    }
                },
                "total": {
                    "description": "Total number of items available",
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaginatedResponse-github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto_UserDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "List of items in the current page",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.UserDTO"
                    }
                },
                "total": {
                    "description": "Total number of items available",
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaymentHistoryDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "amount_due": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "credit_account_id": {
                    "type": "integer"
                },
                "days_late": {
                    "type": "integer"
                },
                "debt_id": {
                    "type": "integer"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "payment_date": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonAddressDTO": {
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDTO": {
            "type": "object",
            "required": [
                "personal_information"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "credit_accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.CreditAccountDTO"
                    }
                },
                "credit_inquiries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.CreditInquiryDTO"
                    }
                },
                "credit_score": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.CreditScoreDTO"
                },
                "credit_score_id": {
                    "type": "integer"
                },
                "data_sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.DataSourceDTO"
                    }
                },
                "debts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.DebtDTO"
                    }
                },
                "employment_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.EmploymentRecordDTO"
                    }
                },
                "financial_profile": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FinancialProfileDTO"
                },
                "financial_profile_id": {
                    "type": "integer"
                },
                "fraud_alerts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FraudAlertDTO"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "last_verified_at": {
                    "type": "string"
                },
                "legal_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.LegalRecordDTO"
                    }
                },
                "negative_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.NegativeRecordDTO"
                    }
                },
                "payment_histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PaymentHistoryDTO"
                    }
                },
                "personal_information": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonalInformationDTO"
                },
                "personal_information_id": {
                    "type": "integer"
                },
                "related_persons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonRelationshipDTO"
                    }
                },
                "risk_assessments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.RiskAssessmentDTO"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDocumentDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "document_type": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "file": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FileDTO"
                },
                "id": {
                    "type": "integer"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "verified_at": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonRelationshipDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "person_id": {
                    "type": "integer"
                },
                "related_person_id": {
                    "type": "integer"
                },
                "relation_type": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verification_status": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonalInformationDTO": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonAddressDTO"
                    }
                },
                "alternative_email": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "document": {
                    "type": "string",
                    "example": "12345678909"
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDocumentDTO"
                    }
                },
                "email": {
                    "type": "string"
                },
                "email_verified": {
                    "type": "boolean"
                },
                "full_name": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marital_status": {
                    "type": "string"
                },
                "mother_name": {
                    "type": "string"
                },
                "nationality": {
                    "type": "string"
                },
                "phone_verified": {
                    "type": "boolean"
                },
                "primary_phone": {
                    "type": "string",
                    "example": "11999999999"
                },
                "profile_photo": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.FileDTO"
                },
                "rg": {
                    "type": "string"
                },
                "rg_issue_date": {
                    "type": "string"
                },
                "rg_issuer": {
                    "type": "string"
                },
                "secondary_phone": {
                    "type": "string"
                },
                "voter_id": {
                    "type": "string"
                },
                "work_card": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.RiskAssessmentDTO": {
            "type": "object",
            "properties": {
                "assessment_date": {
                    "type": "string"
                },
                "assessment_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "model_version": {
                    "type": "string"
                },
                "person_id": {
                    "type": "integer"
                },
                "recommendation": {
                    "type": "string"
                },
                "risk_factors": {
                    "type": "string"
                },
                "risk_level": {
                    "type": "string"
                },
                "risk_score": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.UserDTO": {
            "type": "object",
            "required": [
                "email",
                "password",
                "user_type"
            ],
            "properties": {
                "additional_information_required": {
                    "type": "boolean",
                    "example": false
                },
                "admin": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AdminDTO"
                },
                "analyst": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.AnalystDTO"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "example": "P@ssw0rd!"
                },
                "person": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_dto.PersonDTO"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string",
                    "example": "person | owner | admin | analyst"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.FileRequest": {
            "type": "object",
            "required": [
                "original_name",
                "url"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/file.jpg"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonAddressRequest": {
            "type": "object",
            "required": [
                "address_id"
            ],
            "properties": {
                "address_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonDocumentRequest": {
            "type": "object",
            "required": [
                "document_type"
            ],
            "properties": {
                "document_type": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "file": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.FileRequest"
                },
                "id": {
                    "type": "integer"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "verified_at": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                }
            }
        },
        "github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonalInformationRequest": {
            "type": "object",
            "required": [
                "document",
                "full_name"
            ],
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonAddressRequest"
                    }
                },
                "alternative_email": {
                    "type": "string"
                },
                "biometric_validated": {
                    "type": "boolean"
                },
                "birth_date": {
                    "type": "string"
                },
                "document": {
                    "type": "string",
                    "example": "12345678909"
                },
                "document_validated": {
                    "type": "boolean"
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.PersonDocumentRequest"
                    }
                },
                "email": {
                    "type": "string"
                },
                "email_verified": {
                    "type": "boolean"
                },
                "full_name": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marital_status": {
                    "type": "string"
                },
                "mother_name": {
                    "type": "string"
                },
                "nationality": {
                    "type": "string"
                },
                "phone_verified": {
                    "type": "boolean"
                },
                "primary_phone": {
                    "type": "string",
                    "example": "11999999999"
                },
                "profile_photo": {
                    "$ref": "#/definitions/github_com_BrunoPolaski_bureau-mcp-server_internal_infra_controllers_request.FileRequest"
                },
                "receita_federal_status": {
                    "type": "string"
                },
                "rg": {
                    "type": "string"
                },
                "rg_issue_date": {
                    "type": "string"
                },
                "rg_issuer": {
                    "type": "string"
                },
                "secondary_phone": {
                    "type": "string"
                },
                "voter_id": {
                    "type": "string"
                },
                "work_card": {
                    "type": "string"
                }
            }
        },
        "rest_err.Causes": {
            "type": "object",
            "properties": {
                "field": {
                    "description": "Field or parameter that caused the error",
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "description": "Description of the cause",
                    "type": "string",
                    "example": "invalid email address"
                }
            }
        },
        "rest_err.RestErr": {
            "type": "object",
            "properties": {
                "causes": {
                    "description": "Detailed error causes, most common for json field validation errors",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest_err.Causes"
                    }
                },
                "code": {
                    "description": "HTTP status code",
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "bad request"
                },
                "message": {
                    "description": "Human readable message",
                    "type": "string",
                    "example": "invalid request parameters"
                },
                "timestamp": {
                    "description": "When the error occurred",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-api-key",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        },
        "CookieAuth": {
            "type": "apiKey",
            "name": "Sid",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Bureau API",
	Description:      "This is the API documentation for the Bureau MCP Server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
